---
event_type: IssuesEvent
avatar: "https://avatars.githubusercontent.com/u/814322?"
user: vsoch
date: 2020-09-21
repo_name: vsoch/pull-request-action
html_url: https://github.com/vsoch/pull-request-action/issues/41
repo_url: https://github.com/vsoch/pull-request-action
---

<a href='https://github.com/vsoch' target='_blank'>vsoch</a> closed issue <a href='https://github.com/vsoch/pull-request-action/issues/41' target='_blank'>vsoch/pull-request-action#41</a>.

<p>Failing action status when all looks good</p><small>Hi, I have this response (in a private repository), where the pull request is successfully created, but the status check is `error`:...</small><a href='https://github.com/vsoch/pull-request-action/issues/41' target='_blank'>View Comment</a>